// This code is generated by github.com/davyxu/protoc-gen-sharpnet, DO NOT EDIT
// Generated from: test.proto
namespace gamedef
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Profile")]
	public partial class Profile : global::ProtoBuf.IExtensible
	{
		public Profile() {}
		
		private int _Age = default(int);
		[global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"Age", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int Age
		{
			get { return _Age; }
			set { _Age = value; }
		}
		
		private string _Name = "";
		[global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Name
		{
			get { return _Name; }
			set { _Name = value; }
		}
		
		private gamedef.JobType _Job = gamedef.JobType.None;
		[global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"Job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(gamedef.JobType.None)]
		public gamedef.JobType Job
		{
			get { return _Job; }
			set { _Job = value; }
		}
		
		private double _Double = default(double);
		[global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"Double", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(double))]
		public double Double
		{
			get { return _Double; }
			set { _Double = value; }
		}
		
		private bool _Single = default(bool);
		[global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"Single", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool Single
		{
			get { return _Single; }
			set { _Single = value; }
		}
		
		private readonly global::System.Collections.Generic.List<long> _IDs = new global::System.Collections.Generic.List<long>();
		[global::ProtoBuf.ProtoMember(100, Name=@"IDs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		public global::System.Collections.Generic.List<long> IDs
		{
			get { return _IDs; }
		}
		
		[global::ProtoBuf.ProtoContract(Name=@"MsgID")]
		public enum MsgID
		{
			[global::ProtoBuf.ProtoEnum(Name=@"ID", Value=0)]
			ID = 0
			
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
	[global::ProtoBuf.ProtoContract(Name=@"JobType")]
	public enum JobType
	{
		[global::ProtoBuf.ProtoEnum(Name=@"None", Value=0)]
		None = 0,
		
		[global::ProtoBuf.ProtoEnum(Name=@"Student", Value=1)]
		Student = 1,
		
		[global::ProtoBuf.ProtoEnum(Name=@"Worker", Value=2)]
		Worker = 2
		
	}
}
