// Generated by github.com/davyxu/protoc-gen-sharpnet
// DO NOT EDIT!
// Source: test.proto
namespace gamedef
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Profile")]
	public partial class Profile : global::ProtoBuf.IExtensible
	{
		public Profile() {}
		
		int _Age = default(int);
		bool _hasAge = false;
		[global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"Age", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int Age
		{
			get { return _Age; }
			set { _Age = value; 
			      _hasAge = true;
			}
		}
		
		public bool HasAge
		{
			get { return _hasAge; }
			set { _hasAge = value; }
		}
		
		string _Name = "";
		bool _hasName = false;
		[global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Name
		{
			get { return _Name; }
			set { _Name = value; 
			      _hasName = true;
			}
		}
		
		public bool HasName
		{
			get { return _hasName; }
			set { _hasName = value; }
		}
		
		gamedef.JobType _Job = gamedef.JobType.None;
		bool _hasJob = false;
		[global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"Job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(gamedef.JobType.None)]
		public gamedef.JobType Job
		{
			get { return _Job; }
			set { _Job = value; 
			      _hasJob = true;
			}
		}
		
		public bool HasJob
		{
			get { return _hasJob; }
			set { _hasJob = value; }
		}
		
		double _Double = default(double);
		bool _hasDouble = false;
		[global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"Double", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(double))]
		public double Double
		{
			get { return _Double; }
			set { _Double = value; 
			      _hasDouble = true;
			}
		}
		
		public bool HasDouble
		{
			get { return _hasDouble; }
			set { _hasDouble = value; }
		}
		
		bool _Single = default(bool);
		bool _hasSingle = false;
		[global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"Single", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool Single
		{
			get { return _Single; }
			set { _Single = value; 
			      _hasSingle = true;
			}
		}
		
		public bool HasSingle
		{
			get { return _hasSingle; }
			set { _hasSingle = value; }
		}
		
		readonly global::System.Collections.Generic.List<long> _IDs = new global::System.Collections.Generic.List<long>();
		[global::ProtoBuf.ProtoMember(100, Name=@"IDs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		public global::System.Collections.Generic.List<long> IDs
		{
			get { return _IDs; }
		}
		
		public bool HasIDs
		{
			get { return _hasIDs; }
			set { _hasIDs = value; }
		}
		
		[global::ProtoBuf.ProtoContract(Name=@"MsgID")]
		public enum MsgID
		{
			[global::ProtoBuf.ProtoEnum(Name=@"ID", Value=0)]
			ID = 0
			
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
	[global::ProtoBuf.ProtoContract(Name=@"JobType")]
	public enum JobType
	{
		[global::ProtoBuf.ProtoEnum(Name=@"None", Value=0)]
		None = 0,
		
		[global::ProtoBuf.ProtoEnum(Name=@"Student", Value=1)]
		Student = 1,
		
		[global::ProtoBuf.ProtoEnum(Name=@"Worker", Value=2)]
		Worker = 2
		
	}
}
