package main

import (
	"github.com/davyxu/pbmeta"
)

func printFile(gen *Generator, file *pbmeta.FileDescriptor) {

	gen.Println("// Generated by github.com/davyxu/protoc-gen-sharpnet")
	gen.Println("// DO NOT EDIT!")
	gen.Println("// Source: ", file.FileName())

	gen.In()
	for _, v := range file.Define.Dependency {
		gen.Println("// ", v)
	}
	gen.Out()

	gen.Println("namespace ", file.PackageName())
	gen.Println("{")
	gen.In()

	for i := 0; i < file.MessageCount(); i++ {

		msg := file.Message(i)
		printMessage(gen, msg, file)
	}

	gen.Println()

	for i := 0; i < file.EnumCount(); i++ {

		enum := file.Enum(i)
		printEnum(gen, enum)
	}

	gen.Out()
	gen.Println("}")
}
